# Table of Contents
### 1. Importing Libraries
### 2. Importing Data
### 3. Task: Grouping Data & Aggregating Variables
### 4. Exporting Data

# 01. Importing Libraries

In [2]:
# Import Libraries
import pandas as pd
import numpy as np
import os

# 02. Importing Data

In [3]:
# Creating Path
path = r'/Users/mattwawner/Documents/8-2022-Instacart Basket Analysis'

In [4]:
# Importing df_orders_products_merged
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_busy_columns_47.pkl'))

# 03. Task - Grouping Data & Aggregating Variables

### 2. Find the aggregated mean of the 'order_number' column grouped by 'department_id' for the entire dataframe

In [5]:
# Finding the aggregated mean of the 'order_number' column grouped by 'department_id'

ords_prods_merge.groupby('department_id')['order_number'].mean()

department_id
1     15.457838
2     17.277920
3     17.170395
4     17.811403
5     15.213779
6     16.439806
7     17.225802
8     15.340650
9     15.895474
10    20.197148
11    16.171095
12    15.887671
13    16.583536
14    16.771241
15    16.165037
16    17.665606
17    15.694469
18    19.310397
19    17.177343
20    16.473447
21    22.902379
Name: order_number, dtype: float64

### 3. Analyze the result

   #### The results of the entire dataframe do not differ too much from those of the subset

### 4. Create a loyalty flag for existing customers using the transform( ) and loc( ) functions

#### This was completed during the exercise in a different notebook

In [6]:
# Displaying the 'max_order' & 'loyalty_flag' columns created during the exercise

ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_of_week,busiest_hours_of_day,max_order,loyalty_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,32,Regular customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,32,Regular customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,7.0,10,0,both,Mid-range product,Regularly busy,Least busy days,Average orders,3,New customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Least busy days,Average orders,3,New customer

### 5. Check the basic statistics of the product prices for each loyalty category

In [7]:
# Viewing stats of groups based on loyalty

ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'max', 'min','median']})

                     prices
                       mean      max  min median
loyalty_flag
Loyal customer    10.386229  99999.0  1.0    7.4
New customer      13.294406  99999.0  1.0    7.4
Regular customer  12.495501  99999.0  1.0    7.4

### 6. Create a spending flag for each user based on the average price across all their orders

In [8]:
# Creating an 'avg_prod_price' column to derive the spending flag from

ords_prods_merge['avg_prod_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [9]:
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,...,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_of_week,busiest_hours_of_day,max_order,loyalty_flag,avg_prod_price
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,5,0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,32,Regular customer,6.935811
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,1,1,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,32,Regular customer,6.935811
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,10,0,both,Mid-range product,Regularly busy,Least busy days,Average orders,3,New customer,4.972414
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,11,1,both,Mid-range product,Least busy,Least busy days,Average orders,3,New customer,4.972414

In [10]:
# Flagging users with avg_prod_price < 10 as 'Low spenders'

ords_prods_merge.loc[ords_prods_merge['avg_prod_price'] < 10,
        'spending_flag'] = 'Low spender'

In [11]:
# Flagging users with avg_prod_price >= 10 as 'High spenders'

ords_prods_merge.loc[(ords_prods_merge['avg_prod_price'] >= 10),
         'spending_flag'] = 'High spender'

In [12]:
# Checking the number of high and low spenders

ords_prods_merge['spending_flag'].value_counts(dropna = False)

Low spender     31771789
High spender      634252
Name: spending_flag, dtype: int64

### 7. Create an order frequency flag that marks the regularity of a user's ordering behavior according to the median in the 'day_since_prior_order' column

In [13]:
# Creating an 'med_days_since_prior_order' column to derive the regularity flag from

ords_prods_merge['med_days_since_prior_order'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [14]:
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,...,_merge,price_range_loc,busiest_day,busiest_days_of_week,busiest_hours_of_day,max_order,loyalty_flag,avg_prod_price,spending_flag,med_days_since_prior_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,32,Regular customer,6.935811,Low spender,8.0
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,32,Regular customer,6.935811,Low spender,8.0
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender,7.0
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,both,Mid-range product,Regularly busy,Least busy days,Average orders,3,New customer,4.972414,Low spender,9.0
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,both,Mid-range product,Least busy,Least busy days,Average orders,3,New customer,4.972414,Low spender,9.0

In [15]:
# Flagging users with med_days_since_prior_order > 20 as 'Non-frequent customer'

ords_prods_merge.loc[ords_prods_merge['med_days_since_prior_order'] > 20,
        'regularity_flag'] = 'Non-frequent customer'

In [16]:
# Flagging users with med_days_since_prior_order > 10 & <= 20 as 'Regular customer'

ords_prods_merge.loc[(ords_prods_merge
        ['med_days_since_prior_order'] > 10) & (ords_prods_merge['med_days_since_prior_order'] <= 20),
         'regularity_flag'] = 'Regular customer'

In [17]:
# Flagging users with med_days_since_prior_order <= 10 as 'Frequent customer'

ords_prods_merge.loc[ords_prods_merge['med_days_since_prior_order'] <= 10,
        'regularity_flag'] = 'Frequent customer'

In [18]:
# Checking the frequency of values in regularity_flag column

ords_prods_merge['regularity_flag'].value_counts(dropna = False)

Frequent customer        22790800
Regular customer          6928407
Non-frequent customer     2686834
Name: regularity_flag, dtype: int64

In [19]:
# Checking results of regularity flag

ords_prods_merge.head(75)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,...,price_range_loc,busiest_day,busiest_days_of_week,busiest_hours_of_day,max_order,loyalty_flag,avg_prod_price,spending_flag,med_days_since_prior_order,regularity_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Mid-range product,Regularly busy,Regularly busy days,Average orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender,7.0,Frequent customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,Mid-range product,Regularly busy,Least busy days,Average orders,3,New customer,4.972414,Low spender,9.0,Frequent customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,Mid-range product,Least busy,Least busy days,Average orders,3,New customer,4.972414,Low spender,9.0,Frequent customer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,1,Chocolate Sandwich Cookies,61,19,5.8,3052954,8723,4,3,10,...,Mid-range product,Regularly busy,Least busy days,Most orders,36,Regular customer,5.677397,Low spender,6.0,Frequent customer
71,1,Chocolate Sandwich Cookies,61,19,5.8,1486756,8735,8,4,11,...,Mid-range product,Least busy,Least busy days,Most orders,9,New customer,5.850000,Low spender,24.0,Non-frequent customer
72,1,Chocolate Sandwich Cookies,61,19,5.8,632514,9293,2,0,12,...,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,11.857143,High spender,30.0,Non-frequent customer
73,1,Chocolate Sandwich Cookies,61,19,5.8,1253470,9293,3,3,13,...,Mid-range product,Regularly busy,Least busy days,Average orders,5,New customer,11.857143,High spender,30.0,Non-frequent customer
74,1,Chocolate Sandwich Cookies,61,19,5.8,837303,9467,1,0,17,...,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.709091,Low spender,24.0,Non-frequent customer

# 04. Exporting Data

In [20]:
# Exporting data
ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_newcols_48.pkl'))